import Link from "next/link";

const operator = process.env.NEXT_PUBLIC_OPERATOR_NAME;
const contact = process.env.NEXT_PUBLIC_SUPPORT_EMAIL;

export default function PrivacyPage() {
  return <main className="shell py-10 sm:py-14"><article className="mx-auto max-w-3xl">
    <Link href="/" className="text-sm font-bold text-zinc-400 hover:text-white">← Home</Link>
    <h1 className="mt-5 text-4xl font-black sm:text-5xl">Privacy Policy</h1>
    <p className="mt-3 text-sm text-zinc-500">Last updated: 15 August 2026</p>
    <div className="mt-8 space-y-8 text-zinc-300 leading-7">
      <section><h2 className="text-xl font-black text-white">Operator</h2>{operator ? <p className="mt-2">This service is operated by {operator}.</p> : <p className="mt-2 text-amber-200">Set <code>NEXT_PUBLIC_OPERATOR_NAME</code> to the genuine person or organisation operating the service before production review.</p>}</section>
      <section><h2 className="text-xl font-black text-white">What this service does</h2><p className="mt-2">Who Liked That? is a private multiplayer party game. Players may connect a TikTok account and, where they explicitly authorise it, import a limited set of TikTok activity needed to generate guessing rounds.</p></section>
      <section><h2 className="text-xl font-black text-white">Information we process</h2><p className="mt-2">We process an internal account identifier, your chosen in-game display name, room membership and game results. If you connect TikTok, we may store your TikTok Open ID, display name, avatar URL, granted scopes and encrypted OAuth tokens. If you import TikTok activity, we store only the activity records needed by the game, such as liked-video identifiers, video URLs and activity dates where available.</p></section>
      <section><h2 className="text-xl font-black text-white">TikTok data portability</h2><p className="mt-2">Where TikTok Data Portability access is available, the service requests a one-time export only after you choose to import your activity. The service extracts the Like List required for gameplay and does not intentionally retain unrelated archive contents. Raw portability archives are processed transiently and are not saved as permanent application records.</p></section>
      <section><h2 className="text-xl font-black text-white">Manual archive import</h2><p className="mt-2">If you choose manual import, the archive is parsed in your browser first. Only the extracted liked-video records are sent to the application server in batches. This reduces the amount of unrelated TikTok archive information sent to us.</p></section>
      <section><h2 className="text-xl font-black text-white">How game data is shared</h2><p className="mt-2">Other room members receive only the activity selected for a current round and the information necessary to play. Your complete imported TikTok activity history is not sent to other players. The correct owner of a round is not sent to clients before the reveal state.</p></section>
      <section><h2 className="text-xl font-black text-white">Storage and security</h2><p className="mt-2">Application data is stored in Supabase-hosted PostgreSQL. TikTok access and refresh tokens are stored server-side in encrypted form and are not exposed to browser JavaScript. Access to application data is restricted using server-side controls and database row-level security where applicable.</p></section>
      <section><h2 className="text-xl font-black text-white">Retention and deletion</h2><p className="mt-2">Imported TikTok activity is kept until you delete it, disconnect and request deletion, or the operator removes it as part of account or service maintenance. The Account page provides controls to disconnect TikTok and to delete imported TikTok data. A TikTok deauthorisation webhook also removes the stored TikTok connection and associated imported activity when received.</p></section>
      <section><h2 className="text-xl font-black text-white">Third parties</h2><p className="mt-2">The service relies on TikTok for account authorisation and authorised data portability, Supabase for authentication/database services, and Vercel for web hosting. Those providers process information under their own terms and privacy policies.</p></section>
      <section><h2 className="text-xl font-black text-white">Your choices</h2><p className="mt-2">You can use the service without importing TikTok activity where that gameplay mode is available. You can revoke TikTok access through TikTok, disconnect it in this application, and delete imported TikTok activity from the Account page.</p></section>
      <section><h2 className="text-xl font-black text-white">Access and data-subject requests</h2><p className="mt-2">You can use the Account page for immediate TikTok-data deletion. For an access request, a copy of application data associated with you, correction, restriction or another privacy request, contact the support address below. We may need reasonable information to verify that the request relates to your account before disclosing or changing data.</p></section>
      <section><h2 className="text-xl font-black text-white">Contact</h2>{contact ? <p className="mt-2">Privacy and support enquiries: <a className="underline" href={`mailto:${contact}`}>{contact}</a>.</p> : <p className="mt-2 text-amber-200">A public support email must be configured before production review. Set <code>NEXT_PUBLIC_SUPPORT_EMAIL</code> in Vercel.</p>}</section>
    </div>
  </article></main>;
}
